name: Node CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ">=16.0.0"
      - name: Install npm dependencies
        run: yarn install
      - name: Run build task
        run: CI="" yarn build:production
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/build/, /node_modules/"
